# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane



#-----------------------------------------------------------------------------------------
# Helper methods for versioning pubspec.yaml
#-----------------------------------------------------------------------------------------

def get_pubspec_version
  pubspec = File.read("../../pubspec.yaml")
  version_line = pubspec.lines.find { |line| line.start_with?("version:") }
  version = version_line.split(":").last.strip
  return version
end

def increment_version_name(version)
  major, minor, patch = version.split(".").map(&:to_i)

  if patch < 9
    patch += 1
  else
    patch = 0
    if minor < 9
      minor += 1
    else
      minor = 0
      major += 1
    end
  end

  "#{major}.#{minor}.#{patch}"
end


def update_pubspec(new_version_name, new_build_number)
  pubspec_path = "../../pubspec.yaml"
  pubspec = File.read(pubspec_path)

  new_version_line = "version: #{new_version_name}+#{new_build_number}"
  updated_pubspec = pubspec.gsub(/^version: .+$/, new_version_line)

  File.write(pubspec_path, updated_pubspec)
  puts("Updated pubspec.yaml to version #{new_version_name}+#{new_build_number}")
end

#-----------------------------------------------------------------------------------------
# End of helper methods for versioning pubspec.yaml
#-----------------------------------------------------------------------------------------`

default_platform(:ios)

platform :ios do
  desc "Build and upload to TestFlight"
  lane :beta do

    # --- 1. Authenticate with App Store Connect ---
    app_store_connect_api_key(
      key_id: ENV["APP_STORE_CONNECT_API_KEY_ID"],
      issuer_id: ENV["APP_STORE_CONNECT_ISSUER_ID"],
      key_content: ENV["APP_STORE_CONNECT_KEY"],
      is_key_content_base64: true
    )

    # --- 2. Create and unlock CI keychain ---
    keychain_path = File.expand_path("~/Library/Keychains/build.keychain")
    create_keychain(
      path: keychain_path,
      password: ENV["MATCH_PASSWORD"],
      default_keychain: true,
      unlock: true,
      timeout: 3600
    )

    # --- 3. Install certificates + provisioning profiles ---
    match(
      type: "appstore",
      readonly: false,
      git_url: ENV["MATCH_GIT_URL"],
      keychain_name: "build.keychain",
      keychain_password: ENV["MATCH_PASSWORD"]
    )

    # --- 4. Ensure keychain stays unlocked ---
    sh "security set-keychain-settings -lut 21600 #{keychain_path}"

    # --- 5. Increment build number ---
    # TODO: current_version = get_version_number(target: "Runner")
    

    #TODO:
    # 5.0. Use current pubspec version to Get latest build number from App Store
    # latest_build = latest_testflight_build_number(
    #   version: current_version,
    #   app_identifier: "com.kodeit.scriptureunion"
    # ) || 0
    # puts("Latest build number from App Store: #{current_version} #{latest_build}")
    

    #TODO:
  # 5.1. Read current pubspec version and build number
    # pubspec_version = get_pubspec_version
    # puts("Current pubspec version: #{pubspec_version}")

    #NEW ADDITION
    # 1. Fetch the latest build number
  # If you don't provide a 'version', it returns the latest build of the latest version.
  build_number = latest_testflight_build_number(
    app_identifier: "com.kodeit.scriptureunion", # Automatically uses Appfile if available
    api_key: lane_context[SharedValues::APP_STORE_CONNECT_API_KEY] # Recommended for 2026
  )

  # 2. Access the Version Name (e.g., "1.2.0") from lane_context
  version_name = lane_context[SharedValues::LATEST_TESTFLIGHT_VERSION]

  puts "Latest TestFlight Version: #{version_name}"
  puts "Latest TestFlight Build Number: #{build_number}"


  # 5.3. Increment current version name eg: (1.0.8 -> 1.0.9)
    new_version_name = increment_version_name(version_name)
    puts("New version name: #{new_version_name}")

  # 5.4. Increment appstore build number
    new_build_number = build_number + 1
    puts("New build number and version name: #{new_version_name} #{new_build_number}")

  # 5.4. Update pubspec.yaml
    update_pubspec(new_version_name, new_build_number)

  # 5.5. Update Xcode project
     increment_build_number(
        xcodeproj: "../ios/Runner.xcodeproj",
        build_number: new_build_number
      )
    increment_version_number(version_number: new_version_name)

    sh "sed -i '' 's/\\+.*$/+#{new_build_number}/' ../../pubspec.yaml"

    clear_derived_data

    # --- 6. Build IPA ---
    build_app(
      workspace: "Runner.xcworkspace",
      scheme: "Runner",
      export_method: "app-store",
      clean: true,
      include_bitcode: false,
      export_options: {
        provisioningProfiles: {
          "com.kodeit.scriptureunion" => "match AppStore com.kodeit.scriptureunion"
        }
      }
    )

    # --- 7. Upload to TestFlight ---
    upload_to_testflight(
      skip_waiting_for_build_processing: true,
      changelog: "Automated GitHub Actions build"
    )
  end
end

#-----------------------------------------------------------------------------------------
# Android lane for internal release
#-----------------------------------------------------------------------------------------
platform :android do
  desc "Build and upload a new Android version to the internal track"
  lane :internal_release do
    
    # 1. Get the latest VERSION NAME
    # Removed package_name here (pulled from Appfile)
    names = google_play_track_release_names(
      track: 'alpha',
      json_key_data: ENV['GPLAY_JSON_DATA']
    )
    play_store_version_name = names.first || "1.0.0"
    
    # 2. Get the latest VERSION CODE
    # Removed package_name here (pulled from Appfile)
    codes = google_play_track_version_codes(
      track: 'alpha',
      json_key_data: ENV['GPLAY_JSON_DATA'] # Added missing json_key_data here
    )
    new_version_code = (codes.max || 0) + 1

    # 3. Increment the Version Name
    new_version_name = increment_version_name(play_store_version_name)

    puts("New Version Name: #{new_version_name}")
    puts("New Version Code: #{new_version_code}")

    # 4. Build the App
    gradle(
      task: 'clean bundle',
      build_type: 'Release',
      properties: {
        "android.injected.version.name" => new_version_name,
        "android.injected.version.code" => new_version_code
      }
    )

    # 5. Upload to Play Store
    # Removed package_name here (pulled from Appfile)
    upload_to_play_store(
      track: "alpha",
      aab: "../build/app/outputs/bundle/release/app-release.aab", # Verified path for Flutter
      release_status: "completed",
      json_key_data: ENV['GPLAY_JSON_DATA']
    )
  end
end
