# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane
#-----------------------------------------------------------------------------------------
# Helper methods for versioning pubspec.yaml
#-----------------------------------------------------------------------------------------


def increment_version_name(version)
  major, minor, patch = version.split(".").map(&:to_i)

  if patch < 9
    patch += 1
  else
    patch = 0
    if minor < 9
      minor += 1
    else
      minor = 0
      major += 1
    end
  end

  "#{major}.#{minor}.#{patch}"
end

#-----------------------------------------------------------------------------------------
# End of helper methods for versioning pubspec.yaml
#-----------------------------------------------------------------------------------------`

#-----------------------------------------------------------------------------------------
# Android lane for internal release
#-----------------------------------------------------------------------------------------

default_platform(:android)

platform :android do
  desc "Build and upload a new Android version to the internal track"
  lane :internal_release do
    credentials = ENV['GPLAY_JSON_DATA']
    
     # 1. Safely fetch Version Names
    names = []
    begin
      names = google_play_track_release_names(
        track: 'alpha',
        json_key_data: credentials
      )
    rescue => e
      puts "Notice: Could not fetch release names (Track might be empty): #{e}"
    end
    play_store_version_name = names.first || "1.0.0"
    
    # 2. Safely fetch Version Codes (Fix for the 'flat_map' error)
    codes = []
    begin
      codes = google_play_track_version_codes(
        track: 'alpha',
        json_key_data: credentials
      )
    rescue => e
      # This catches the nil:NilClass error when the track is empty
      puts "Notice: Track 'alpha' is empty. Starting from version code 1."
      codes = [0] 
    end
    
    # Ensure codes is an array even if the action returns nil unexpectedly
    new_version_code = ((codes || [0]).max || 0) + 1

    # 3. Increment the Version Name
    new_version_name = increment_version_name(play_store_version_name)

    puts("New Version Name: #{new_version_name}")
    puts("New Version Code: #{new_version_code}")

    # 4. Build the App
    gradle(
      task: 'clean bundle',
      build_type: 'Release',
      gradle_path: './gradlew', # Explicitly point to the local wrapper
      properties: {
        "android.injected.version.name" => new_version_name,
        "android.injected.version.code" => new_version_code
      }
    )

    # 5. Upload to Play Store
    # Removed package_name here (pulled from Appfile)
    upload_to_play_store(
      track: "alpha",
      aab: "../build/app/outputs/bundle/release/app-release.aab", # Verified path for Flutter
      release_status: "completed",
      json_key_data: credentials
    )
  end
end
